### ISSUE TITLE
 video on the site

### ISSUE THREAD

**Issue by VitArtby** [HitkoDev/Videobox#4]
Hello, please write an example of calling the video on the site. With YouTube it turns out and the file on the website does not work.
What video formats should I use?
Thank you.

**Comment by HitkoDev** [comment]
In case you're looking for informations about Joomla! or MODX versions of Videobox, please refer to the [Getting started](https://hitko.eu/videobox/getting-started/) guide.

Unlike the Joomla! and MODX extensions, this plugin doesn't contain a code parser or own video player, it only contains the UI effects (pop-up, inline player, and slider), along with the corresponding CSS styling. While it gives you full control over the content (such as custom thumbnails / links, and embedding any video player through an ```iframe```), it also means it's your job as a developer to generate the appropriate thumbnails and provide a link to the player (for example ```https://hitko.eu/videobox/adapters/?vb-video=files%2Fvideos%2FOceans+clip.mp4&autoplay=0&color=7a9cff```) in order to insert it.
